In [1]:
# only for test

import csv
import glob, os
import pandas as pd

print('aa')
print(os.path.abspath('.'))

aa
C:\Users\mynam\Documents\GitHub\Video-Player-Controlled-by-Action-Recognition_wkr\src


In [2]:
# initialisation
# TODO: move all packages here but not for now

featureDict = {'down': {} , 'up': {}, 'left': {}, 'right': {}, 'fist': {}}


In [3]:
# load data from csv files
# feature extraction
# TODO: freq-domain features
# TODO: feature selection
# TODO: normalisation

import math
import numpy as np
import csv
import glob, os
import pandas as pd

# locate folers
actionList = ['down', 'up', 'left', 'right', 'fist']
for currentAction in range(len(actionList)):
    filePath = os.path.abspath('./Dataset/hyqData/' + actionList[currentAction])

    print(filePath)


    file = glob.glob(os.path.join(filePath, "*.csv"))


    dl = []
    for f in file:
        dl.append(pd.read_csv(f, header=None))



    # obtain each EMG channel data
    emg_1=[]
    emg_2=[]
    emg_3=[]

    featureList = []

    index=0
    i=0
    for index in range(len(dl)): # access all csv files

        for i in range(len(dl[index].values.tolist())): # access all recorded samples
            emg_1.append(dl[index].values.tolist()[i][0])
            emg_2.append(dl[index].values.tolist()[i][1])
            emg_3.append(dl[index].values.tolist()[i][2])


        ### calculate time-domain features

        # Mean Absolute Value
        MAV_emg_1 = 0
        MAV_emg_2 = 0
        MAV_emg_3 = 0
        # Wavelength
        WL_emg_1 = 0
        WL_emg_2 = 0
        WL_emg_3 = 0
        # Slope Sign Changes
        SSCthreshold = 0 # TODO: detemine the threshold
        SSC_emg_1 = 0
        SSC_emg_2 = 0
        SSC_emg_3 = 0
        # Zero Crossing: we don't have, do we?
        ZC_emg_1 = 0
        ZC_emg_2 = 0
        ZC_emg_3 = 0
        # Root Mean Square
        RMS_emg_1 = 0.0
        RMS_emg_2 = 0.0
        RMS_emg_3 = 0.0

        i=0
        temp1=0
        temp2=0
        temp3=0
        temp4=0
        temp5=0
        temp6=0
        temp7=0.0
        temp8=0.0
        temp9=0.0
        for i in range(len(emg_3)):
            temp1 = temp1 + abs(int(emg_1[i]))
            temp2 = temp2 + abs(int(emg_2[i]))
            temp3 = temp3 + abs(int(emg_3[i]))
            temp7 = temp7 + (int(emg_1[i]))**2
            temp8 = temp8 + (int(emg_2[i]))**2
            temp9 = temp9 + (int(emg_3[i]))**2

            if(i>0):
                WL_emg_1 = WL_emg_1 + abs(int(emg_1[i]) - int(emg_1[i-1]))
                WL_emg_2 = WL_emg_2 + abs(int(emg_2[i]) - int(emg_2[i-1]))
                WL_emg_3 = WL_emg_3 + abs(int(emg_3[i]) - int(emg_3[i-1]))

            if(i>1):
                temp4 = (int(emg_1[i-1]) - int(emg_1[i-2])) * (int(emg_1[i-1]) - int(emg_1[i]))
                temp5 = (int(emg_2[i-1]) - int(emg_2[i-2])) * (int(emg_2[i-1]) - int(emg_2[i]))
                temp6 = (int(emg_3[i-1]) - int(emg_3[i-2])) * (int(emg_3[i-1]) - int(emg_3[i]))
                if temp4 >= SSCthreshold:
                    SSC_emg_1 = SSC_emg_1 + 1
                if temp5 >= SSCthreshold:
                    SSC_emg_2 = SSC_emg_2 + 1
                if temp6 >= SSCthreshold:
                    SSC_emg_3 = SSC_emg_3 + 1



            MAV_emg_1 = temp1/len(emg_1)
            MAV_emg_2 = temp2/len(emg_2)
            MAV_emg_3 = temp3/len(emg_3)

            RMS_emg_1 = math.sqrt(temp7/len(emg_1))
            RMS_emg_2 = math.sqrt(temp8/len(emg_2))
            RMS_emg_3 = math.sqrt(temp9/len(emg_3))

        featureDict[actionList[currentAction]][index] = [MAV_emg_1, MAV_emg_2, MAV_emg_3, WL_emg_1, WL_emg_2, WL_emg_3, SSC_emg_1, SSC_emg_2, SSC_emg_3, RMS_emg_1, RMS_emg_2, RMS_emg_3]


    # print(MAV_emg_1, MAV_emg_2, MAV_emg_3)
    # print(WL_emg_1, WL_emg_2, WL_emg_3)
    # print(SSC_emg_1, SSC_emg_2, SSC_emg_3)
    # print(RMS_emg_1, RMS_emg_2, RMS_emg_3)


C:\Users\mynam\Documents\GitHub\Video-Player-Controlled-by-Action-Recognition_wkr\src\Dataset\hyqData\down
C:\Users\mynam\Documents\GitHub\Video-Player-Controlled-by-Action-Recognition_wkr\src\Dataset\hyqData\up
C:\Users\mynam\Documents\GitHub\Video-Player-Controlled-by-Action-Recognition_wkr\src\Dataset\hyqData\left
C:\Users\mynam\Documents\GitHub\Video-Player-Controlled-by-Action-Recognition_wkr\src\Dataset\hyqData\right
C:\Users\mynam\Documents\GitHub\Video-Player-Controlled-by-Action-Recognition_wkr\src\Dataset\hyqData\fist


In [4]:
# TODO: visualisation (if possible)

print(featureDict.keys())
print(len(featureDict['down']))
print(len(featureDict['up']))
print(len(featureDict['left']))
print(len(featureDict['right']))
print(len(featureDict['fist']))
print(featureDict['down'][0])
print(featureDict['up'][0])
print(featureDict['left'][0])
print(featureDict['right'][0])
print(featureDict['fist'][0])


dict_keys(['down', 'up', 'left', 'right', 'fist'])
25
25
25
25
30
[39.693333333333335, 55.17666666666667, 74.89666666666666, 499, 522, 1652, 219, 196, 215, 46.753894668430206, 64.37931862536809, 170.15286264611203]
[17.243333333333332, 171.14, 105.74333333333334, 40, 1030, 610, 297, 147, 157, 17.271460081108756, 216.06070134725258, 131.5700700514115]
[52.26, 71.05666666666667, 18.476666666666667, 964, 774, 168, 227, 198, 255, 85.64395289024594, 101.17929630117023, 27.522899556551085]
[59.38, 72.19, 59.7, 966, 705, 1261, 195, 174, 232, 76.48424674401913, 85.48288327690716, 137.3561550616984]
[58.67666666666667, 118.07333333333334, 32.553333333333335, 1285, 1341, 802, 226, 168, 234, 103.38170373265604, 130.02540777350657, 53.41891050929436]


In [5]:
# create labels for data samples
# TODO: weight init randomisation

from keras.utils import np_utils
x_train=[]
y_train=[]

def labelSwitch(arg):
    switcher = {
        'left': 1,
        'right': 2,
        'up': 3,
        'down': 4,
        'fist': 5
    }
    return switcher[arg]

i=0
j=''
dictLength=0
current = ['down', 'up', 'left', 'right', 'fist']
for j in range(len(current)):
    for i in range(len(featureDict[current[j]])):
        x_train.append(featureDict[current[j]][i])
        y_train.append(labelSwitch(current[j]))
        dictLength=dictLength+1

x_train = np.array(x_train)
y_train = np.array(y_train).reshape(dictLength,1)

y_train_class = np_utils.to_categorical(y_train)

state = np.random.get_state()
np.random.shuffle(x_train)
np.random.set_state(state)
np.random.shuffle(y_train_class)


In [10]:
# TODO: Model

import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.ERROR)
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.utils import np_utils
from keras.datasets import cifar10
from keras.optimizers import RMSprop
tf.random.set_seed(1234)

model = Sequential()

model.add(Dense(12, activation='tanh', input_shape=(x_train.shape)))
model.add(Dense(50, activation='tanh'))
# model.add(Dropout(0.25))
model.add(Dense(6, activation='softmax'))

# opt = RMSprop(lr=0.1, decay=1e-6)

# Let's train the model using RMSprop
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])
model.fit(x_train, y_train_class, epochs=100, batch_size=130)


# score = model.evaluate(X_test_flatten, Y_test_class, verbose=0)
# print('Test loss:', score[0])
# print('Test accuracy:', score[1])

Epoch 1/100
1/1 [==============================] - 0s 2ms/step - loss: 1.8644 - accuracy: 0.1923
Epoch 2/100
1/1 [==============================] - 0s 1ms/step - loss: 1.8168 - accuracy: 0.1923
Epoch 3/100
1/1 [==============================] - 0s 1000us/step - loss: 1.7721 - accuracy: 0.4000
Epoch 4/100
1/1 [==============================] - 0s 997us/step - loss: 1.7287 - accuracy: 0.5923
Epoch 5/100
1/1 [==============================] - 0s 997us/step - loss: 1.6868 - accuracy: 0.5923
Epoch 6/100
1/1 [==============================] - 0s 998us/step - loss: 1.6462 - accuracy: 0.5923
Epoch 7/100
1/1 [==============================] - 0s 1000us/step - loss: 1.6070 - accuracy: 0.5923
Epoch 8/100
1/1 [==============================] - 0s 995us/step - loss: 1.5691 - accuracy: 0.5769
Epoch 9/100
1/1 [==============================] - 0s 997us/step - loss: 1.5326 - accuracy: 0.5769
Epoch 10/100
1/1 [==============================] - 0s 3ms/step - loss: 1.4974 - accuracy: 0.5769
Epoch 11/100


1/1 [==============================] - 0s 2ms/step - loss: 0.4994 - accuracy: 0.8077
Epoch 84/100
1/1 [==============================] - 0s 997us/step - loss: 0.4952 - accuracy: 0.8077
Epoch 85/100
1/1 [==============================] - 0s 1ms/step - loss: 0.4911 - accuracy: 0.8077
Epoch 86/100
1/1 [==============================] - 0s 997us/step - loss: 0.4871 - accuracy: 0.8077
Epoch 87/100
1/1 [==============================] - 0s 1ms/step - loss: 0.4832 - accuracy: 0.8077
Epoch 88/100
1/1 [==============================] - 0s 997us/step - loss: 0.4794 - accuracy: 0.8077
Epoch 89/100
1/1 [==============================] - 0s 2ms/step - loss: 0.4757 - accuracy: 0.8077
Epoch 90/100
1/1 [==============================] - 0s 2ms/step - loss: 0.4721 - accuracy: 0.8077
Epoch 91/100
1/1 [==============================] - 0s 995us/step - loss: 0.4686 - accuracy: 0.8077
Epoch 92/100
1/1 [==============================] - 0s 996us/step - loss: 0.4651 - accuracy: 0.8077
Epoch 93/100
1/1 [=====

In [102]:
# temp block TBD

print(x_train.shape)
print(y_train.shape)
print(np.min(y_train))
print(y_train_class)

(130, 12)
(130, 1)
1
[[0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0.