In [1]:
# only for test

import csv
import glob, os
import pandas as pd

print('aa')
print(os.path.abspath('.'))

aa
C:\Users\mynam\Documents\GitHub\Video-Player-Controlled-by-Action-Recognition_wkr\src


In [2]:
# initialisation
# TODO: move all packages here but not for now

featureDict = {'down': {} , 'up': {}, 'left': {}, 'right': {}, 'fist': {}}


In [3]:
# load data from csv files
# feature extraction
# TODO: freq-domain features
# TODO: feature selection
# TODO: normalisation

import math
import numpy as np
import csv
import glob, os
import pandas as pd

# locate folers
actionList = ['down', 'up', 'left', 'right', 'fist']
for currentAction in range(len(actionList)):
    filePath = os.path.abspath('./Dataset/hyqData/' + actionList[currentAction])

    print(filePath)


    file = glob.glob(os.path.join(filePath, "*.csv"))


    dl = []
    for f in file:
        dl.append(pd.read_csv(f, header=None))



    # obtain each EMG channel data
    emg_1=[]
    emg_2=[]
    emg_3=[]

    featureList = []

    index=0
    i=0
    for index in range(len(dl)): # access all csv files

        for i in range(len(dl[index].values.tolist())): # access all recorded samples
            emg_1.append(dl[index].values.tolist()[i][0])
            emg_2.append(dl[index].values.tolist()[i][1])
            emg_3.append(dl[index].values.tolist()[i][2])


        ### calculate time-domain features

        # Mean Absolute Value
        MAV_emg_1 = 0
        MAV_emg_2 = 0
        MAV_emg_3 = 0
        # Wavelength
        WL_emg_1 = 0
        WL_emg_2 = 0
        WL_emg_3 = 0
        # Slope Sign Changes
        SSCthreshold = 0 # TODO: detemine the threshold
        SSC_emg_1 = 0
        SSC_emg_2 = 0
        SSC_emg_3 = 0
        # Zero Crossing: we don't have, do we?
        ZC_emg_1 = 0
        ZC_emg_2 = 0
        ZC_emg_3 = 0
        # Root Mean Square
        RMS_emg_1 = 0.0
        RMS_emg_2 = 0.0
        RMS_emg_3 = 0.0

        i=0
        temp1=0
        temp2=0
        temp3=0
        temp4=0
        temp5=0
        temp6=0
        temp7=0.0
        temp8=0.0
        temp9=0.0
        for i in range(len(emg_3)):
            temp1 = temp1 + abs(int(emg_1[i]))
            temp2 = temp2 + abs(int(emg_2[i]))
            temp3 = temp3 + abs(int(emg_3[i]))
            temp7 = temp7 + (int(emg_1[i]))**2
            temp8 = temp8 + (int(emg_2[i]))**2
            temp9 = temp9 + (int(emg_3[i]))**2

            if(i>0):
                WL_emg_1 = WL_emg_1 + abs(int(emg_1[i]) - int(emg_1[i-1]))
                WL_emg_2 = WL_emg_2 + abs(int(emg_2[i]) - int(emg_2[i-1]))
                WL_emg_3 = WL_emg_3 + abs(int(emg_3[i]) - int(emg_3[i-1]))

            if(i>1):
                temp4 = (int(emg_1[i-1]) - int(emg_1[i-2])) * (int(emg_1[i-1]) - int(emg_1[i]))
                temp5 = (int(emg_2[i-1]) - int(emg_2[i-2])) * (int(emg_2[i-1]) - int(emg_2[i]))
                temp6 = (int(emg_3[i-1]) - int(emg_3[i-2])) * (int(emg_3[i-1]) - int(emg_3[i]))
                if temp4 >= SSCthreshold:
                    SSC_emg_1 = SSC_emg_1 + 1
                if temp5 >= SSCthreshold:
                    SSC_emg_2 = SSC_emg_2 + 1
                if temp6 >= SSCthreshold:
                    SSC_emg_3 = SSC_emg_3 + 1



            MAV_emg_1 = temp1/len(emg_1)
            MAV_emg_2 = temp2/len(emg_2)
            MAV_emg_3 = temp3/len(emg_3)

            RMS_emg_1 = math.sqrt(temp7/len(emg_1))
            RMS_emg_2 = math.sqrt(temp8/len(emg_2))
            RMS_emg_3 = math.sqrt(temp9/len(emg_3))

        featureDict[actionList[currentAction]][index] = [MAV_emg_1, MAV_emg_2, MAV_emg_3, WL_emg_1, WL_emg_2, WL_emg_3, SSC_emg_1, SSC_emg_2, SSC_emg_3, RMS_emg_1, RMS_emg_2, RMS_emg_3]


    # print(MAV_emg_1, MAV_emg_2, MAV_emg_3)
    # print(WL_emg_1, WL_emg_2, WL_emg_3)
    # print(SSC_emg_1, SSC_emg_2, SSC_emg_3)
    # print(RMS_emg_1, RMS_emg_2, RMS_emg_3)


C:\Users\mynam\Documents\GitHub\Video-Player-Controlled-by-Action-Recognition_wkr\src\Dataset\hyqData\down
C:\Users\mynam\Documents\GitHub\Video-Player-Controlled-by-Action-Recognition_wkr\src\Dataset\hyqData\up
C:\Users\mynam\Documents\GitHub\Video-Player-Controlled-by-Action-Recognition_wkr\src\Dataset\hyqData\left
C:\Users\mynam\Documents\GitHub\Video-Player-Controlled-by-Action-Recognition_wkr\src\Dataset\hyqData\right
C:\Users\mynam\Documents\GitHub\Video-Player-Controlled-by-Action-Recognition_wkr\src\Dataset\hyqData\fist


In [4]:
# TODO: visualisation (if possible)

print(featureDict.keys())
print(len(featureDict['down']))
print(len(featureDict['up']))
print(len(featureDict['left']))
print(len(featureDict['right']))
print(len(featureDict['fist']))
print(featureDict['down'][0])
print(featureDict['up'][0])
print(featureDict['left'][0])
print(featureDict['right'][0])
print(featureDict['fist'][0])


dict_keys(['down', 'up', 'left', 'right', 'fist'])
25
25
25
25
30
[39.693333333333335, 55.17666666666667, 74.89666666666666, 499, 522, 1652, 219, 196, 215, 46.753894668430206, 64.37931862536809, 170.15286264611203]
[17.243333333333332, 171.14, 105.74333333333334, 40, 1030, 610, 297, 147, 157, 17.271460081108756, 216.06070134725258, 131.5700700514115]
[52.26, 71.05666666666667, 18.476666666666667, 964, 774, 168, 227, 198, 255, 85.64395289024594, 101.17929630117023, 27.522899556551085]
[59.38, 72.19, 59.7, 966, 705, 1261, 195, 174, 232, 76.48424674401913, 85.48288327690716, 137.3561550616984]
[58.67666666666667, 118.07333333333334, 32.553333333333335, 1285, 1341, 802, 226, 168, 234, 103.38170373265604, 130.02540777350657, 53.41891050929436]


In [5]:
# create labels for data samples
# TODO: weight init randomisation

from keras.utils import np_utils
x_train=[]
y_train=[]

def labelSwitch(arg):
    switcher = {
        'left': 1,
        'right': 2,
        'up': 3,
        'down': 4,
        'fist': 5
    }
    return switcher[arg]

i=0
j=''
dictLength=0
current = ['down', 'up', 'left', 'right', 'fist']
for j in range(len(current)):
    for i in range(len(featureDict[current[j]])):
        x_train.append(featureDict[current[j]][i])
        y_train.append(labelSwitch(current[j]))
        dictLength=dictLength+1

x_train = np.array(x_train)
y_train = np.array(y_train).reshape(dictLength,1)

y_train_class = np_utils.to_categorical(y_train)

state = np.random.get_state()
np.random.shuffle(x_train)
np.random.set_state(state)
np.random.shuffle(y_train_class)


In [15]:
# TODO: Model

import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.ERROR)
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.utils import np_utils
from keras.datasets import cifar10
from keras.optimizers import RMSprop
tf.random.set_seed(1234)

model = Sequential()

model.add(Dense(12, activation='sigmoid', input_shape=(x_train.shape)))
model.add(Dense(50, activation='sigmoid'))
model.add(Dense(50, activation='sigmoid'))
model.add(Dense(50, activation='sigmoid'))
model.add(Dense(50, activation='sigmoid'))
#model.add(Dropout(0.1))
model.add(Dense(6, activation='sigmoid'))

# opt = RMSprop(lr=0.1, decay=1e-6)

# Let's train the model using RMSprop
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])
model.fit(x_train, y_train_class, epochs=1000, batch_size=130)


# score = model.evaluate(X_test_flatten, Y_test_class, verbose=0)
# print('Test loss:', score[0])
# print('Test accuracy:', score[1])

Epoch 1/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.8648 - accuracy: 0.1923
Epoch 2/1000
1/1 [==============================] - 0s 997us/step - loss: 1.8495 - accuracy: 0.1923
Epoch 3/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.8349 - accuracy: 0.1923
Epoch 4/1000
1/1 [==============================] - 0s 1ms/step - loss: 1.8210 - accuracy: 0.1923
Epoch 5/1000
1/1 [==============================] - 0s 977us/step - loss: 1.8077 - accuracy: 0.1923
Epoch 6/1000
1/1 [==============================] - 0s 1ms/step - loss: 1.7951 - accuracy: 0.1923
Epoch 7/1000
1/1 [==============================] - 0s 995us/step - loss: 1.7832 - accuracy: 0.1923
Epoch 8/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.7719 - accuracy: 0.2308
Epoch 9/1000
1/1 [==============================] - 0s 998us/step - loss: 1.7613 - accuracy: 0.2308
Epoch 10/1000
1/1 [==============================] - 0s 997us/step - loss: 1.7513 - accuracy: 0.2308
Epoch 11/

1/1 [==============================] - 0s 997us/step - loss: 1.6121 - accuracy: 0.2308
Epoch 83/1000
1/1 [==============================] - 0s 997us/step - loss: 1.6119 - accuracy: 0.2308
Epoch 84/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.6117 - accuracy: 0.2308
Epoch 85/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.6116 - accuracy: 0.2308
Epoch 86/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.6114 - accuracy: 0.2308
Epoch 87/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.6113 - accuracy: 0.2308
Epoch 88/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.6111 - accuracy: 0.2308
Epoch 89/1000
1/1 [==============================] - 0s 995us/step - loss: 1.6110 - accuracy: 0.2308
Epoch 90/1000
1/1 [==============================] - 0s 998us/step - loss: 1.6108 - accuracy: 0.2308
Epoch 91/1000
1/1 [==============================] - 0s 998us/step - loss: 1.6107 - accuracy: 0.2308
Epoch 92/1000


Epoch 163/1000
1/1 [==============================] - 0s 998us/step - loss: 1.5226 - accuracy: 0.4231
Epoch 164/1000
1/1 [==============================] - 0s 998us/step - loss: 1.5164 - accuracy: 0.4231
Epoch 165/1000
1/1 [==============================] - 0s 995us/step - loss: 1.5099 - accuracy: 0.4231
Epoch 166/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.5030 - accuracy: 0.4231
Epoch 167/1000
1/1 [==============================] - 0s 998us/step - loss: 1.4957 - accuracy: 0.4231
Epoch 168/1000
1/1 [==============================] - 0s 998us/step - loss: 1.4881 - accuracy: 0.4231
Epoch 169/1000
1/1 [==============================] - 0s 996us/step - loss: 1.4801 - accuracy: 0.4231
Epoch 170/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.4718 - accuracy: 0.4231
Epoch 171/1000
1/1 [==============================] - 0s 2ms/step - loss: 1.4632 - accuracy: 0.4231
Epoch 172/1000
1/1 [==============================] - 0s 999us/step - loss: 1.4543 - acc

1/1 [==============================] - 0s 2ms/step - loss: 0.7794 - accuracy: 0.6077
Epoch 244/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.7735 - accuracy: 0.6077
Epoch 245/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.7678 - accuracy: 0.6077
Epoch 246/1000
1/1 [==============================] - 0s 998us/step - loss: 0.7622 - accuracy: 0.6077
Epoch 247/1000
1/1 [==============================] - 0s 996us/step - loss: 0.7568 - accuracy: 0.6077
Epoch 248/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.7514 - accuracy: 0.6077
Epoch 249/1000
1/1 [==============================] - 0s 997us/step - loss: 0.7462 - accuracy: 0.6077
Epoch 250/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.7411 - accuracy: 0.6077
Epoch 251/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.7361 - accuracy: 0.6077
Epoch 252/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.7312 - accuracy: 0.6077
Epoch 253

1/1 [==============================] - 0s 2ms/step - loss: 0.4796 - accuracy: 0.8077
Epoch 325/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4768 - accuracy: 0.8077
Epoch 326/1000
1/1 [==============================] - 0s 997us/step - loss: 0.4740 - accuracy: 0.8077
Epoch 327/1000
1/1 [==============================] - 0s 998us/step - loss: 0.4712 - accuracy: 0.8077
Epoch 328/1000
1/1 [==============================] - 0s 999us/step - loss: 0.4685 - accuracy: 0.8077
Epoch 329/1000
1/1 [==============================] - 0s 996us/step - loss: 0.4658 - accuracy: 0.8077
Epoch 330/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4631 - accuracy: 0.8077
Epoch 331/1000
1/1 [==============================] - 0s 995us/step - loss: 0.4605 - accuracy: 0.8077
Epoch 332/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4579 - accuracy: 0.8077
Epoch 333/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.4553 - accuracy: 0.8077
Epoch

1/1 [==============================] - 0s 997us/step - loss: 0.3485 - accuracy: 0.8077
Epoch 406/1000
1/1 [==============================] - 0s 997us/step - loss: 0.3477 - accuracy: 0.8077
Epoch 407/1000
1/1 [==============================] - 0s 997us/step - loss: 0.3469 - accuracy: 0.8077
Epoch 408/1000
1/1 [==============================] - 0s 998us/step - loss: 0.3462 - accuracy: 0.8077
Epoch 409/1000
1/1 [==============================] - 0s 968us/step - loss: 0.3455 - accuracy: 0.8077
Epoch 410/1000
1/1 [==============================] - 0s 994us/step - loss: 0.3447 - accuracy: 0.8077
Epoch 411/1000
1/1 [==============================] - 0s 995us/step - loss: 0.3440 - accuracy: 0.8077
Epoch 412/1000
1/1 [==============================] - 0s 997us/step - loss: 0.3433 - accuracy: 0.8077
Epoch 413/1000
1/1 [==============================] - 0s 997us/step - loss: 0.3426 - accuracy: 0.8077
Epoch 414/1000
1/1 [==============================] - 0s 997us/step - loss: 0.3419 - accuracy: 0.

1/1 [==============================] - 0s 971us/step - loss: 0.3090 - accuracy: 0.8077
Epoch 487/1000
1/1 [==============================] - 0s 997us/step - loss: 0.3087 - accuracy: 0.8077
Epoch 488/1000
1/1 [==============================] - 0s 995us/step - loss: 0.3084 - accuracy: 0.8077
Epoch 489/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3081 - accuracy: 0.8077
Epoch 490/1000
1/1 [==============================] - 0s 995us/step - loss: 0.3078 - accuracy: 0.8077
Epoch 491/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.3075 - accuracy: 0.8077
Epoch 492/1000
1/1 [==============================] - 0s 997us/step - loss: 0.3072 - accuracy: 0.8077
Epoch 493/1000
1/1 [==============================] - 0s 996us/step - loss: 0.3069 - accuracy: 0.8077
Epoch 494/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3066 - accuracy: 0.8077
Epoch 495/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.3063 - accuracy: 0.8077
Epo

1/1 [==============================] - 0s 2ms/step - loss: 0.2917 - accuracy: 0.8077
Epoch 568/1000
1/1 [==============================] - 0s 997us/step - loss: 0.2916 - accuracy: 0.8077
Epoch 569/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2915 - accuracy: 0.8077
Epoch 570/1000
1/1 [==============================] - 0s 999us/step - loss: 0.2913 - accuracy: 0.8077
Epoch 571/1000
1/1 [==============================] - 0s 997us/step - loss: 0.2912 - accuracy: 0.8077
Epoch 572/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2911 - accuracy: 0.8077
Epoch 573/1000
1/1 [==============================] - 0s 999us/step - loss: 0.2909 - accuracy: 0.8077
Epoch 574/1000
1/1 [==============================] - 0s 996us/step - loss: 0.2908 - accuracy: 0.8077
Epoch 575/1000
1/1 [==============================] - 0s 995us/step - loss: 0.2907 - accuracy: 0.8077
Epoch 576/1000
1/1 [==============================] - 0s 997us/step - loss: 0.2906 - accuracy: 0.8077
E

1/1 [==============================] - 0s 997us/step - loss: 0.2838 - accuracy: 0.8077
Epoch 648/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.2837 - accuracy: 0.8077
Epoch 649/1000
1/1 [==============================] - 0s 993us/step - loss: 0.2837 - accuracy: 0.8077
Epoch 650/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.2836 - accuracy: 0.8077
Epoch 651/1000
1/1 [==============================] - 0s 998us/step - loss: 0.2835 - accuracy: 0.8077
Epoch 652/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.2834 - accuracy: 0.8077
Epoch 653/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2834 - accuracy: 0.8077
Epoch 654/1000
1/1 [==============================] - 0s 996us/step - loss: 0.2833 - accuracy: 0.8077
Epoch 655/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2832 - accuracy: 0.8077
Epoch 656/1000
1/1 [==============================] - 0s 998us/step - loss: 0.2832 - accuracy: 0.8077
Epoch

1/1 [==============================] - 0s 997us/step - loss: 0.2793 - accuracy: 0.8077
Epoch 728/1000
1/1 [==============================] - 0s 994us/step - loss: 0.2792 - accuracy: 0.8077
Epoch 729/1000
1/1 [==============================] - 0s 997us/step - loss: 0.2792 - accuracy: 0.8077
Epoch 730/1000
1/1 [==============================] - 0s 998us/step - loss: 0.2792 - accuracy: 0.8077
Epoch 731/1000
1/1 [==============================] - 0s 997us/step - loss: 0.2791 - accuracy: 0.8077
Epoch 732/1000
1/1 [==============================] - 0s 998us/step - loss: 0.2791 - accuracy: 0.8077
Epoch 733/1000
1/1 [==============================] - 0s 998us/step - loss: 0.2790 - accuracy: 0.8077
Epoch 734/1000
1/1 [==============================] - 0s 998us/step - loss: 0.2790 - accuracy: 0.8077
Epoch 735/1000
1/1 [==============================] - 0s 997us/step - loss: 0.2789 - accuracy: 0.8077
Epoch 736/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2789 - accuracy: 0.80

Epoch 808/1000
1/1 [==============================] - 0s 998us/step - loss: 0.2762 - accuracy: 0.8077
Epoch 809/1000
1/1 [==============================] - 0s 998us/step - loss: 0.2762 - accuracy: 0.8077
Epoch 810/1000
1/1 [==============================] - 0s 998us/step - loss: 0.2762 - accuracy: 0.8077
Epoch 811/1000
1/1 [==============================] - 0s 998us/step - loss: 0.2761 - accuracy: 0.8077
Epoch 812/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.2761 - accuracy: 0.8077
Epoch 813/1000
1/1 [==============================] - 0s 963us/step - loss: 0.2761 - accuracy: 0.8077
Epoch 814/1000
1/1 [==============================] - 0s 998us/step - loss: 0.2760 - accuracy: 0.8077
Epoch 815/1000
1/1 [==============================] - 0s 998us/step - loss: 0.2760 - accuracy: 0.8077
Epoch 816/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.2760 - accuracy: 0.8077
Epoch 817/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.2759 - acc

1/1 [==============================] - 0s 2ms/step - loss: 0.2738 - accuracy: 0.8154
Epoch 889/1000
1/1 [==============================] - 0s 993us/step - loss: 0.2737 - accuracy: 0.8154
Epoch 890/1000
1/1 [==============================] - 0s 993us/step - loss: 0.2737 - accuracy: 0.8154
Epoch 891/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2737 - accuracy: 0.8154
Epoch 892/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2736 - accuracy: 0.8154
Epoch 893/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2736 - accuracy: 0.8154
Epoch 894/1000
1/1 [==============================] - 0s 997us/step - loss: 0.2736 - accuracy: 0.8154
Epoch 895/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2736 - accuracy: 0.8154
Epoch 896/1000
1/1 [==============================] - 0s 997us/step - loss: 0.2735 - accuracy: 0.8154
Epoch 897/1000
1/1 [==============================] - 0s 2ms/step - loss: 0.2735 - accuracy: 0.8154
Epoch 8

1/1 [==============================] - 0s 998us/step - loss: 0.2716 - accuracy: 0.8154
Epoch 969/1000
1/1 [==============================] - 0s 997us/step - loss: 0.2716 - accuracy: 0.8154
Epoch 970/1000
1/1 [==============================] - 0s 998us/step - loss: 0.2716 - accuracy: 0.8154
Epoch 971/1000
1/1 [==============================] - 0s 1ms/step - loss: 0.2715 - accuracy: 0.8154
Epoch 972/1000
1/1 [==============================] - 0s 997us/step - loss: 0.2715 - accuracy: 0.8154
Epoch 973/1000
1/1 [==============================] - 0s 997us/step - loss: 0.2715 - accuracy: 0.8154
Epoch 974/1000
1/1 [==============================] - 0s 998us/step - loss: 0.2715 - accuracy: 0.8154
Epoch 975/1000
1/1 [==============================] - 0s 995us/step - loss: 0.2715 - accuracy: 0.8154
Epoch 976/1000
1/1 [==============================] - 0s 997us/step - loss: 0.2714 - accuracy: 0.8154
Epoch 977/1000
1/1 [==============================] - 0s 994us/step - loss: 0.2714 - accuracy: 0.81

In [102]:
# temp block TBD

print(x_train.shape)
print(y_train.shape)
print(np.min(y_train))
print(y_train_class)

(130, 12)
(130, 1)
1
[[0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0.