In [1]:
# only for test

import csv
import glob, os
import pandas as pd

print('aa')
print(os.path.abspath('.'))

aa
C:\Users\mynam\Documents\GitHub\Video-Player-Controlled-by-Action-Recognition_wkr\src


In [2]:
# initialisation
# TODO: move all packages here but not for now

featureDict = {'down': {} , 'up': {}, 'left': {}, 'right': {}, 'fist': {}}


In [3]:
# load data from csv files
# feature extraction
# TODO: freq-domain features
# TODO: feature selection
# TODO: normalisation

import math
import numpy as np
import csv
import glob, os
import pandas as pd

# locate folers
actionList = ['down', 'up', 'left', 'right', 'fist']
for currentAction in range(len(actionList)):
    filePath = os.path.abspath('./Dataset/hyqData/' + actionList[currentAction])

    print(filePath)


    file = glob.glob(os.path.join(filePath, "*.csv"))


    dl = []
    for f in file:
        dl.append(pd.read_csv(f, header=None))



    # obtain each EMG channel data
    emg_1=[]
    emg_2=[]
    emg_3=[]

    featureList = []

    index=0
    i=0
    for index in range(len(dl)): # access all csv files

        for i in range(len(dl[index].values.tolist())): # access all recorded samples
            emg_1.append(dl[index].values.tolist()[i][0])
            emg_2.append(dl[index].values.tolist()[i][1])
            emg_3.append(dl[index].values.tolist()[i][2])


        ### calculate time-domain features

        # Mean Absolute Value
        MAV_emg_1 = 0
        MAV_emg_2 = 0
        MAV_emg_3 = 0
        # Wavelength
        WL_emg_1 = 0
        WL_emg_2 = 0
        WL_emg_3 = 0
        # Slope Sign Changes
        SSCthreshold = 0 # TODO: detemine the threshold
        SSC_emg_1 = 0
        SSC_emg_2 = 0
        SSC_emg_3 = 0
        # Zero Crossing: we don't have, do we?
        ZC_emg_1 = 0
        ZC_emg_2 = 0
        ZC_emg_3 = 0
        # Root Mean Square
        RMS_emg_1 = 0.0
        RMS_emg_2 = 0.0
        RMS_emg_3 = 0.0

        i=0
        temp1=0
        temp2=0
        temp3=0
        temp4=0
        temp5=0
        temp6=0
        temp7=0.0
        temp8=0.0
        temp9=0.0
        for i in range(len(emg_3)):
            temp1 = temp1 + abs(int(emg_1[i]))
            temp2 = temp2 + abs(int(emg_2[i]))
            temp3 = temp3 + abs(int(emg_3[i]))
            temp7 = temp7 + (int(emg_1[i]))**2
            temp8 = temp8 + (int(emg_2[i]))**2
            temp9 = temp9 + (int(emg_3[i]))**2

            if(i>0):
                WL_emg_1 = WL_emg_1 + abs(int(emg_1[i]) - int(emg_1[i-1]))
                WL_emg_2 = WL_emg_2 + abs(int(emg_2[i]) - int(emg_2[i-1]))
                WL_emg_3 = WL_emg_3 + abs(int(emg_3[i]) - int(emg_3[i-1]))

            if(i>1):
                temp4 = (int(emg_1[i-1]) - int(emg_1[i-2])) * (int(emg_1[i-1]) - int(emg_1[i]))
                temp5 = (int(emg_2[i-1]) - int(emg_2[i-2])) * (int(emg_2[i-1]) - int(emg_2[i]))
                temp6 = (int(emg_3[i-1]) - int(emg_3[i-2])) * (int(emg_3[i-1]) - int(emg_3[i]))
                if temp4 >= SSCthreshold:
                    SSC_emg_1 = SSC_emg_1 + 1
                if temp5 >= SSCthreshold:
                    SSC_emg_2 = SSC_emg_2 + 1
                if temp6 >= SSCthreshold:
                    SSC_emg_3 = SSC_emg_3 + 1



            MAV_emg_1 = temp1/len(emg_1)
            MAV_emg_2 = temp2/len(emg_2)
            MAV_emg_3 = temp3/len(emg_3)

            RMS_emg_1 = math.sqrt(temp7/len(emg_1))
            RMS_emg_2 = math.sqrt(temp8/len(emg_2))
            RMS_emg_3 = math.sqrt(temp9/len(emg_3))

        featureDict[actionList[currentAction]][index] = [MAV_emg_1, MAV_emg_2, MAV_emg_3, WL_emg_1, WL_emg_2, WL_emg_3, SSC_emg_1, SSC_emg_2, SSC_emg_3, RMS_emg_1, RMS_emg_2, RMS_emg_3]


    # print(MAV_emg_1, MAV_emg_2, MAV_emg_3)
    # print(WL_emg_1, WL_emg_2, WL_emg_3)
    # print(SSC_emg_1, SSC_emg_2, SSC_emg_3)
    # print(RMS_emg_1, RMS_emg_2, RMS_emg_3)


C:\Users\mynam\Documents\GitHub\Video-Player-Controlled-by-Action-Recognition_wkr\src\Dataset\hyqData\down
C:\Users\mynam\Documents\GitHub\Video-Player-Controlled-by-Action-Recognition_wkr\src\Dataset\hyqData\up
C:\Users\mynam\Documents\GitHub\Video-Player-Controlled-by-Action-Recognition_wkr\src\Dataset\hyqData\left
C:\Users\mynam\Documents\GitHub\Video-Player-Controlled-by-Action-Recognition_wkr\src\Dataset\hyqData\right
C:\Users\mynam\Documents\GitHub\Video-Player-Controlled-by-Action-Recognition_wkr\src\Dataset\hyqData\fist


In [4]:
# TODO: visualisation (if possible)

print(featureDict.keys())
print(len(featureDict['down']))
print(len(featureDict['up']))
print(len(featureDict['left']))
print(len(featureDict['right']))
print(len(featureDict['fist']))
print(featureDict['down'][0])
print(featureDict['up'][0])
print(featureDict['left'][0])
print(featureDict['right'][0])
print(featureDict['fist'][0])


dict_keys(['down', 'up', 'left', 'right', 'fist'])
25
25
25
25
30
[39.693333333333335, 55.17666666666667, 74.89666666666666, 499, 522, 1652, 219, 196, 215, 46.753894668430206, 64.37931862536809, 170.15286264611203]
[17.243333333333332, 171.14, 105.74333333333334, 40, 1030, 610, 297, 147, 157, 17.271460081108756, 216.06070134725258, 131.5700700514115]
[52.26, 71.05666666666667, 18.476666666666667, 964, 774, 168, 227, 198, 255, 85.64395289024594, 101.17929630117023, 27.522899556551085]
[59.38, 72.19, 59.7, 966, 705, 1261, 195, 174, 232, 76.48424674401913, 85.48288327690716, 137.3561550616984]
[58.67666666666667, 118.07333333333334, 32.553333333333335, 1285, 1341, 802, 226, 168, 234, 103.38170373265604, 130.02540777350657, 53.41891050929436]


In [5]:
# create labels for data samples
# TODO: weight init randomisation

from keras.utils import np_utils
x_train=[]
y_train=[]

def labelSwitch(arg):
    switcher = {
        'left': 1,
        'right': 2,
        'up': 3,
        'down': 4,
        'fist': 5
    }
    return switcher[arg]

i=0
j=''
dictLength=0
current = ['down', 'up', 'left', 'right', 'fist']
for j in range(len(current)):
    for i in range(len(featureDict[current[j]])):
        x_train.append(featureDict[current[j]][i])
        y_train.append(labelSwitch(current[j]))
        dictLength=dictLength+1

x_train = np.array(x_train)
y_train = np.array(y_train).reshape(dictLength,1)

y_train_class = np_utils.to_categorical(y_train)

state = np.random.get_state()
np.random.shuffle(x_train)
np.random.set_state(state)
np.random.shuffle(y_train_class)


In [17]:
# TODO: Model

import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.ERROR)
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.utils import np_utils
from keras.datasets import cifar10
from keras.optimizers import RMSprop
tf.random.set_seed(1234)

model = Sequential()

model.add(Dense(12, activation='sigmoid', input_shape=(x_train.shape)))
model.add(Dense(50, activation='sigmoid'))
model.add(Dense(50, activation='sigmoid'))
model.add(Dense(50, activation='sigmoid'))
model.add(Dense(50, activation='sigmoid'))
model.add(Dropout(0.1))
model.add(Dense(6, activation='sigmoid'))

# opt = RMSprop(lr=0.1, decay=1e-6)

# Let's train the model using RMSprop
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])
model.fit(x_train, y_train_class, epochs=2000, batch_size=130)


# score = model.evaluate(X_test_flatten, Y_test_class, verbose=0)
# print('Test loss:', score[0])
# print('Test accuracy:', score[1])

Epoch 1/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.8666 - accuracy: 0.2077
Epoch 2/2000
1/1 [==============================] - 0s 1ms/step - loss: 1.8518 - accuracy: 0.2077
Epoch 3/2000
1/1 [==============================] - 0s 997us/step - loss: 1.8513 - accuracy: 0.2154
Epoch 4/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.8230 - accuracy: 0.2154
Epoch 5/2000
1/1 [==============================] - 0s 997us/step - loss: 1.8223 - accuracy: 0.2000
Epoch 6/2000
1/1 [==============================] - 0s 999us/step - loss: 1.8040 - accuracy: 0.1615
Epoch 7/2000
1/1 [==============================] - 0s 998us/step - loss: 1.7932 - accuracy: 0.2385
Epoch 8/2000
1/1 [==============================] - 0s 998us/step - loss: 1.7807 - accuracy: 0.1923
Epoch 9/2000
1/1 [==============================] - 0s 1ms/step - loss: 1.7773 - accuracy: 0.2000
Epoch 10/2000
1/1 [==============================] - 0s 1000us/step - loss: 1.7686 - accuracy: 0.1769
Epoch 

1/1 [==============================] - 0s 999us/step - loss: 1.6185 - accuracy: 0.2308
Epoch 83/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.6100 - accuracy: 0.2308
Epoch 84/2000
1/1 [==============================] - 0s 999us/step - loss: 1.6170 - accuracy: 0.1846
Epoch 85/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.6058 - accuracy: 0.2462
Epoch 86/2000
1/1 [==============================] - 0s 996us/step - loss: 1.6092 - accuracy: 0.2615
Epoch 87/2000
1/1 [==============================] - 0s 997us/step - loss: 1.6184 - accuracy: 0.2077
Epoch 88/2000
1/1 [==============================] - 0s 998us/step - loss: 1.6188 - accuracy: 0.2231
Epoch 89/2000
1/1 [==============================] - 0s 998us/step - loss: 1.6162 - accuracy: 0.2154
Epoch 90/2000
1/1 [==============================] - 0s 1ms/step - loss: 1.6142 - accuracy: 0.2385
Epoch 91/2000
1/1 [==============================] - 0s 1ms/step - loss: 1.5972 - accuracy: 0.2538
Epoch 92/200

1/1 [==============================] - 0s 996us/step - loss: 1.5882 - accuracy: 0.2385
Epoch 164/2000
1/1 [==============================] - 0s 997us/step - loss: 1.6037 - accuracy: 0.2154
Epoch 165/2000
1/1 [==============================] - 0s 1ms/step - loss: 1.5976 - accuracy: 0.2231
Epoch 166/2000
1/1 [==============================] - 0s 1000us/step - loss: 1.5803 - accuracy: 0.2231
Epoch 167/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.5835 - accuracy: 0.2154
Epoch 168/2000
1/1 [==============================] - 0s 994us/step - loss: 1.5940 - accuracy: 0.2462
Epoch 169/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.5952 - accuracy: 0.2000
Epoch 170/2000
1/1 [==============================] - 0s 995us/step - loss: 1.5988 - accuracy: 0.2385
Epoch 171/2000
1/1 [==============================] - 0s 998us/step - loss: 1.5908 - accuracy: 0.2231
Epoch 172/2000
1/1 [==============================] - 0s 995us/step - loss: 1.5902 - accuracy: 0.2308


1/1 [==============================] - 0s 2ms/step - loss: 1.0898 - accuracy: 0.6385
Epoch 245/2000
1/1 [==============================] - 0s 1ms/step - loss: 1.0876 - accuracy: 0.6615
Epoch 246/2000
1/1 [==============================] - 0s 998us/step - loss: 1.0888 - accuracy: 0.6692
Epoch 247/2000
1/1 [==============================] - 0s 1ms/step - loss: 1.0656 - accuracy: 0.6615
Epoch 248/2000
1/1 [==============================] - 0s 1ms/step - loss: 1.0616 - accuracy: 0.6846
Epoch 249/2000
1/1 [==============================] - 0s 997us/step - loss: 1.0511 - accuracy: 0.6769
Epoch 250/2000
1/1 [==============================] - 0s 1ms/step - loss: 1.0450 - accuracy: 0.6308
Epoch 251/2000
1/1 [==============================] - 0s 2ms/step - loss: 1.0118 - accuracy: 0.7154
Epoch 252/2000
1/1 [==============================] - 0s 1ms/step - loss: 1.0131 - accuracy: 0.7077
Epoch 253/2000
1/1 [==============================] - 0s 996us/step - loss: 1.0281 - accuracy: 0.6077
Epoch 254

1/1 [==============================] - 0s 1ms/step - loss: 0.5996 - accuracy: 0.7692
Epoch 326/2000
1/1 [==============================] - 0s 994us/step - loss: 0.5974 - accuracy: 0.7923
Epoch 327/2000
1/1 [==============================] - 0s 994us/step - loss: 0.6047 - accuracy: 0.7615
Epoch 328/2000
1/1 [==============================] - 0s 998us/step - loss: 0.5877 - accuracy: 0.7538
Epoch 329/2000
1/1 [==============================] - 0s 971us/step - loss: 0.6166 - accuracy: 0.7000
Epoch 330/2000
1/1 [==============================] - 0s 1000us/step - loss: 0.5908 - accuracy: 0.8000
Epoch 331/2000
1/1 [==============================] - 0s 997us/step - loss: 0.5938 - accuracy: 0.7769
Epoch 332/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.5754 - accuracy: 0.8385
Epoch 333/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.5777 - accuracy: 0.8154
Epoch 334/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.5930 - accuracy: 0.7538
Ep

1/1 [==============================] - 0s 998us/step - loss: 0.4118 - accuracy: 0.8462
Epoch 407/2000
1/1 [==============================] - 0s 996us/step - loss: 0.4273 - accuracy: 0.8077
Epoch 408/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.4125 - accuracy: 0.8385
Epoch 409/2000
1/1 [==============================] - 0s 998us/step - loss: 0.4269 - accuracy: 0.8231
Epoch 410/2000
1/1 [==============================] - 0s 997us/step - loss: 0.4192 - accuracy: 0.7692
Epoch 411/2000
1/1 [==============================] - 0s 997us/step - loss: 0.4136 - accuracy: 0.7923
Epoch 412/2000
1/1 [==============================] - 0s 996us/step - loss: 0.4122 - accuracy: 0.8231
Epoch 413/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.4032 - accuracy: 0.7923
Epoch 414/2000
1/1 [==============================] - 0s 0s/step - loss: 0.4271 - accuracy: 0.8077
Epoch 415/2000
1/1 [==============================] - 0s 999us/step - loss: 0.4250 - accuracy: 0.7769
Ep

Epoch 487/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3542 - accuracy: 0.7692
Epoch 488/2000
1/1 [==============================] - 0s 997us/step - loss: 0.3436 - accuracy: 0.8000
Epoch 489/2000
1/1 [==============================] - 0s 995us/step - loss: 0.3517 - accuracy: 0.8308
Epoch 490/2000
1/1 [==============================] - 0s 997us/step - loss: 0.3470 - accuracy: 0.8077
Epoch 491/2000
1/1 [==============================] - 0s 998us/step - loss: 0.3615 - accuracy: 0.8000
Epoch 492/2000
1/1 [==============================] - 0s 997us/step - loss: 0.3569 - accuracy: 0.8000
Epoch 493/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.3400 - accuracy: 0.8231
Epoch 494/2000
1/1 [==============================] - 0s 997us/step - loss: 0.3550 - accuracy: 0.8077
Epoch 495/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3647 - accuracy: 0.7692
Epoch 496/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.3459 - accur

1/1 [==============================] - 0s 2ms/step - loss: 0.3221 - accuracy: 0.7923
Epoch 568/2000
1/1 [==============================] - 0s 997us/step - loss: 0.3133 - accuracy: 0.8000
Epoch 569/2000
1/1 [==============================] - 0s 998us/step - loss: 0.3162 - accuracy: 0.8231
Epoch 570/2000
1/1 [==============================] - 0s 999us/step - loss: 0.3175 - accuracy: 0.7846
Epoch 571/2000
1/1 [==============================] - 0s 999us/step - loss: 0.3146 - accuracy: 0.7846
Epoch 572/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3240 - accuracy: 0.8000
Epoch 573/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3156 - accuracy: 0.7923
Epoch 574/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3234 - accuracy: 0.8154
Epoch 575/2000
1/1 [==============================] - 0s 997us/step - loss: 0.3107 - accuracy: 0.8154
Epoch 576/2000
1/1 [==============================] - 0s 997us/step - loss: 0.3235 - accuracy: 0.8000
Epo

1/1 [==============================] - 0s 997us/step - loss: 0.3017 - accuracy: 0.7923
Epoch 649/2000
1/1 [==============================] - 0s 998us/step - loss: 0.3013 - accuracy: 0.7846
Epoch 650/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.3014 - accuracy: 0.8154
Epoch 651/2000
1/1 [==============================] - 0s 997us/step - loss: 0.3042 - accuracy: 0.7692
Epoch 652/2000
1/1 [==============================] - 0s 996us/step - loss: 0.3083 - accuracy: 0.7692
Epoch 653/2000
1/1 [==============================] - 0s 997us/step - loss: 0.3009 - accuracy: 0.8077
Epoch 654/2000
1/1 [==============================] - 0s 999us/step - loss: 0.2901 - accuracy: 0.8231
Epoch 655/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2872 - accuracy: 0.8538
Epoch 656/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.3043 - accuracy: 0.8308
Epoch 657/2000
1/1 [==============================] - 0s 997us/step - loss: 0.3106 - accuracy: 0.7538
E

1/1 [==============================] - 0s 1000us/step - loss: 0.3040 - accuracy: 0.7692
Epoch 730/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2842 - accuracy: 0.8231
Epoch 731/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2911 - accuracy: 0.7923
Epoch 732/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2898 - accuracy: 0.8462
Epoch 733/2000
1/1 [==============================] - 0s 996us/step - loss: 0.2935 - accuracy: 0.8077
Epoch 734/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2926 - accuracy: 0.8000
Epoch 735/2000
1/1 [==============================] - 0s 1000us/step - loss: 0.2924 - accuracy: 0.8000
Epoch 736/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2984 - accuracy: 0.7692
Epoch 737/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2970 - accuracy: 0.7846
Epoch 738/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2916 - accuracy: 0.8385

1/1 [==============================] - 0s 2ms/step - loss: 0.2789 - accuracy: 0.8615
Epoch 810/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2923 - accuracy: 0.8231
Epoch 811/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2793 - accuracy: 0.8154
Epoch 812/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2820 - accuracy: 0.8308
Epoch 813/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2918 - accuracy: 0.8154
Epoch 814/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2865 - accuracy: 0.8154
Epoch 815/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2896 - accuracy: 0.8077
Epoch 816/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2905 - accuracy: 0.7615
Epoch 817/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2974 - accuracy: 0.7692
Epoch 818/2000
1/1 [==============================] - 0s 1000us/step - loss: 0.2912 - accuracy: 0.784

1/1 [==============================] - 0s 997us/step - loss: 0.2878 - accuracy: 0.7692
Epoch 891/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2897 - accuracy: 0.7769
Epoch 892/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2870 - accuracy: 0.7615
Epoch 893/2000
1/1 [==============================] - 0s 999us/step - loss: 0.2806 - accuracy: 0.8000
Epoch 894/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2837 - accuracy: 0.8000
Epoch 895/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2797 - accuracy: 0.8154
Epoch 896/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2788 - accuracy: 0.8538
Epoch 897/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2832 - accuracy: 0.7846
Epoch 898/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2758 - accuracy: 0.8538
Epoch 899/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2837 - accuracy: 0.8385
Epoch

1/1 [==============================] - 0s 2ms/step - loss: 0.2821 - accuracy: 0.8000
Epoch 972/2000
1/1 [==============================] - 0s 996us/step - loss: 0.2703 - accuracy: 0.8692
Epoch 973/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2738 - accuracy: 0.8615
Epoch 974/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2800 - accuracy: 0.8077
Epoch 975/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2698 - accuracy: 0.8538
Epoch 976/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2815 - accuracy: 0.8000
Epoch 977/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2800 - accuracy: 0.8154
Epoch 978/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2753 - accuracy: 0.8231
Epoch 979/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2802 - accuracy: 0.8077
Epoch 980/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2859 - accuracy: 0.7615
Epoch

1/1 [==============================] - 0s 996us/step - loss: 0.2815 - accuracy: 0.7923
Epoch 1052/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2819 - accuracy: 0.7615
Epoch 1053/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2727 - accuracy: 0.8462
Epoch 1054/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2781 - accuracy: 0.7923
Epoch 1055/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2800 - accuracy: 0.8077
Epoch 1056/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2745 - accuracy: 0.8538
Epoch 1057/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2789 - accuracy: 0.8077
Epoch 1058/2000
1/1 [==============================] - 0s 996us/step - loss: 0.2776 - accuracy: 0.8308
Epoch 1059/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2810 - accuracy: 0.7923
Epoch 1060/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2819 - accuracy: 0

1/1 [==============================] - 0s 2ms/step - loss: 0.2774 - accuracy: 0.8000
Epoch 1132/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2802 - accuracy: 0.7923
Epoch 1133/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2779 - accuracy: 0.8154
Epoch 1134/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2730 - accuracy: 0.8462
Epoch 1135/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2784 - accuracy: 0.8077
Epoch 1136/2000
1/1 [==============================] - 0s 1000us/step - loss: 0.2778 - accuracy: 0.8000
Epoch 1137/2000
1/1 [==============================] - 0s 994us/step - loss: 0.2734 - accuracy: 0.8154
Epoch 1138/2000
1/1 [==============================] - 0s 1000us/step - loss: 0.2754 - accuracy: 0.8077
Epoch 1139/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2743 - accuracy: 0.8231
Epoch 1140/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2766 - accuracy:

1/1 [==============================] - 0s 999us/step - loss: 0.2766 - accuracy: 0.7923
Epoch 1212/2000
1/1 [==============================] - 0s 995us/step - loss: 0.2760 - accuracy: 0.8077
Epoch 1213/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2740 - accuracy: 0.8462
Epoch 1214/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2711 - accuracy: 0.8692
Epoch 1215/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2762 - accuracy: 0.7846
Epoch 1216/2000
1/1 [==============================] - 0s 995us/step - loss: 0.2680 - accuracy: 0.8308
Epoch 1217/2000
1/1 [==============================] - 0s 1000us/step - loss: 0.2768 - accuracy: 0.8000
Epoch 1218/2000
1/1 [==============================] - 0s 996us/step - loss: 0.2731 - accuracy: 0.8154
Epoch 1219/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2752 - accuracy: 0.7846
Epoch 1220/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2741 - accu

1/1 [==============================] - 0s 1ms/step - loss: 0.2752 - accuracy: 0.7769
Epoch 1292/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2735 - accuracy: 0.8154
Epoch 1293/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2696 - accuracy: 0.8462
Epoch 1294/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2733 - accuracy: 0.8000
Epoch 1295/2000
1/1 [==============================] - 0s 999us/step - loss: 0.2747 - accuracy: 0.8000
Epoch 1296/2000
1/1 [==============================] - 0s 996us/step - loss: 0.2708 - accuracy: 0.8077
Epoch 1297/2000
1/1 [==============================] - 0s 993us/step - loss: 0.2671 - accuracy: 0.8846
Epoch 1298/2000
1/1 [==============================] - 0s 996us/step - loss: 0.2807 - accuracy: 0.7769
Epoch 1299/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2753 - accuracy: 0.8077
Epoch 1300/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2771 - accuracy: 0.7

1/1 [==============================] - 0s 998us/step - loss: 0.2684 - accuracy: 0.8538
Epoch 1372/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2678 - accuracy: 0.8231
Epoch 1373/2000
1/1 [==============================] - 0s 999us/step - loss: 0.2681 - accuracy: 0.8462
Epoch 1374/2000
1/1 [==============================] - 0s 999us/step - loss: 0.2747 - accuracy: 0.7846
Epoch 1375/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2727 - accuracy: 0.8077
Epoch 1376/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2668 - accuracy: 0.8231
Epoch 1377/2000
1/1 [==============================] - 0s 1000us/step - loss: 0.2732 - accuracy: 0.8308
Epoch 1378/2000
1/1 [==============================] - 0s 995us/step - loss: 0.2682 - accuracy: 0.8231
Epoch 1379/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2698 - accuracy: 0.8154
Epoch 1380/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2654 - accuracy

1/1 [==============================] - 0s 2ms/step - loss: 0.2726 - accuracy: 0.7846
Epoch 1452/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2710 - accuracy: 0.8231
Epoch 1453/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2734 - accuracy: 0.7923
Epoch 1454/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2677 - accuracy: 0.8385
Epoch 1455/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2673 - accuracy: 0.8231
Epoch 1456/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2737 - accuracy: 0.7769
Epoch 1457/2000
1/1 [==============================] - 0s 1000us/step - loss: 0.2690 - accuracy: 0.8308
Epoch 1458/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2708 - accuracy: 0.8154
Epoch 1459/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2712 - accuracy: 0.8308
Epoch 1460/2000
1/1 [==============================] - 0s 999us/step - loss: 0.2702 - accuracy: 0.79

1/1 [==============================] - 0s 1ms/step - loss: 0.2708 - accuracy: 0.8385
Epoch 1531/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2678 - accuracy: 0.8462
Epoch 1532/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2668 - accuracy: 0.8538
Epoch 1533/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2692 - accuracy: 0.8000
Epoch 1534/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2700 - accuracy: 0.8154
Epoch 1535/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2718 - accuracy: 0.7692
Epoch 1536/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2669 - accuracy: 0.7923
Epoch 1537/2000
1/1 [==============================] - 0s 1000us/step - loss: 0.2731 - accuracy: 0.7846
Epoch 1538/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2671 - accuracy: 0.8538
Epoch 1539/2000
1/1 [==============================] - 0s 999us/step - loss: 0.2705 - accuracy

1/1 [==============================] - 0s 1ms/step - loss: 0.2659 - accuracy: 0.8385
Epoch 1611/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2684 - accuracy: 0.8231
Epoch 1612/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2716 - accuracy: 0.7923
Epoch 1613/2000
1/1 [==============================] - 0s 994us/step - loss: 0.2679 - accuracy: 0.8308
Epoch 1614/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2659 - accuracy: 0.8385
Epoch 1615/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2660 - accuracy: 0.8308
Epoch 1616/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2645 - accuracy: 0.8692
Epoch 1617/2000
1/1 [==============================] - 0s 999us/step - loss: 0.2747 - accuracy: 0.7538
Epoch 1618/2000
1/1 [==============================] - 0s 999us/step - loss: 0.2681 - accuracy: 0.8077
Epoch 1619/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2658 - accuracy: 0.8

1/1 [==============================] - 0s 2ms/step - loss: 0.2667 - accuracy: 0.7923
Epoch 1691/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2701 - accuracy: 0.8077
Epoch 1692/2000
1/1 [==============================] - 0s 996us/step - loss: 0.2674 - accuracy: 0.8000
Epoch 1693/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2700 - accuracy: 0.8077
Epoch 1694/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2669 - accuracy: 0.8385
Epoch 1695/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2689 - accuracy: 0.7846
Epoch 1696/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2656 - accuracy: 0.8308
Epoch 1697/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2659 - accuracy: 0.8385
Epoch 1698/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2715 - accuracy: 0.7769
Epoch 1699/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2666 - accuracy: 0.830

1/1 [==============================] - 0s 997us/step - loss: 0.2680 - accuracy: 0.7846
Epoch 1771/2000
1/1 [==============================] - 0s 996us/step - loss: 0.2700 - accuracy: 0.7769
Epoch 1772/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2684 - accuracy: 0.8000
Epoch 1773/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2719 - accuracy: 0.7538
Epoch 1774/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2698 - accuracy: 0.8308
Epoch 1775/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2635 - accuracy: 0.8615
Epoch 1776/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2681 - accuracy: 0.8308
Epoch 1777/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2674 - accuracy: 0.8308
Epoch 1778/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2697 - accuracy: 0.7615
Epoch 1779/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2710 - accuracy: 0.7

1/1 [==============================] - 0s 2ms/step - loss: 0.2688 - accuracy: 0.8154
Epoch 1851/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2672 - accuracy: 0.7846
Epoch 1852/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2680 - accuracy: 0.7923
Epoch 1853/2000
1/1 [==============================] - 0s 999us/step - loss: 0.2707 - accuracy: 0.7846
Epoch 1854/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2640 - accuracy: 0.8308
Epoch 1855/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2667 - accuracy: 0.8231
Epoch 1856/2000
1/1 [==============================] - 0s 996us/step - loss: 0.2704 - accuracy: 0.8077
Epoch 1857/2000
1/1 [==============================] - 0s 996us/step - loss: 0.2669 - accuracy: 0.7846
Epoch 1858/2000
1/1 [==============================] - 0s 998us/step - loss: 0.2694 - accuracy: 0.8154
Epoch 1859/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2668 - accuracy: 0.8

1/1 [==============================] - 0s 998us/step - loss: 0.2665 - accuracy: 0.8077
Epoch 1930/2000
1/1 [==============================] - 0s 996us/step - loss: 0.2659 - accuracy: 0.8385
Epoch 1931/2000
1/1 [==============================] - 0s 1000us/step - loss: 0.2714 - accuracy: 0.7308
Epoch 1932/2000
1/1 [==============================] - 0s 997us/step - loss: 0.2648 - accuracy: 0.8538
Epoch 1933/2000
1/1 [==============================] - 0s 999us/step - loss: 0.2660 - accuracy: 0.8231
Epoch 1934/2000
1/1 [==============================] - 0s 994us/step - loss: 0.2686 - accuracy: 0.8000
Epoch 1935/2000
1/1 [==============================] - 0s 1ms/step - loss: 0.2700 - accuracy: 0.7923
Epoch 1936/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2655 - accuracy: 0.8154
Epoch 1937/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2640 - accuracy: 0.8154
Epoch 1938/2000
1/1 [==============================] - 0s 2ms/step - loss: 0.2637 - accuracy: 

In [102]:
# temp block TBD

print(x_train.shape)
print(y_train.shape)
print(np.min(y_train))
print(y_train_class)

(130, 12)
(130, 1)
1
[[0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0.